### ISSUE TITLE
Error: fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

### ISSUE THREAD

**Issue by MoOx** [steelbrain/exec#13]
Following https://github.com/AtomLinter/linter-eslint/issues/564

```
Error: (node:1458) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
    at ChildProcess.<anonymous> (/Users/MoOx/setup/dotfiles/.atom/packages/linter-eslint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

This appears when I update Node to 6.x.

**Comment by steelbrain** [comment]
Node v6 is a quite buggy release with several bugs in different areas, this is not a problem in this package but in `eslint` that is not being run under Node v6. The error stack points out that the error is coming from the `stderr` of the spawned process.

To resolve this issue, I would recommend you downgrade your node to a more stable version

**Comment by Arcanemagus** [comment]
From discussion with @steelbrain it sounds like this is simply being repeated from the `stderr` of whatever linter you were using at the time. Do you happen to know what file you were editing when this showed up?

**Comment by MoOx** [comment]
Yeah. It happened for linter-eslint and linter-flow for all my files (private project).

**Comment by Arcanemagus** [comment]
Does `flow` itself work after the update to Node v6?

**Comment by MoOx** [comment]
It seems to.

**Comment by hgwood** [comment]
See https://github.com/nodejs/node/pull/5102.
