### ISSUE TITLE
Wrap arguments in " if necessary on Windows

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/exec#17]
On Windows it seems that wrapping the arguments in `"` is necessary, possibly only if proxying calls through `cmd` which is filed as #16.

For reference Atom does that [here](https://github.com/atom/atom/blob/d3ee21941a78c16695efe9b8e634a8f2921acf47/src/buffered-process.coffee#L58-L63).

**Comment by steelbrain** [comment]
Thanks 👍
