### ISSUE TITLE
Add ignoreExitCode?

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/exec#20]
It seems there is at least one linter (`reek`) that outputs everything to `stdout`, but if it finds something wrong with a file it sets the exit code to `2`. Should an option like `ignoreExitCode` be added to account for this?

**Comment by steelbrain** [comment]
Sounds fair

**Comment by steelbrain** [comment]
On a second thought, can't that plugin just use `streams: 'both'` and then just take the stdout?

**Comment by Arcanemagus** [comment]
It can as a workaround, but that doesn't really make sense. There should never be output on `stderr`, so it would have to re-implement throwing on that if it sees any.
