### ISSUE TITLE
Negative integer arguments break inside Atom

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/exec#27]
![image](https://cloud.githubusercontent.com/assets/427137/16019662/e52cb642-315e-11e6-8413-5824fede3b8a.png)

When an argument is a negative integer, [this line](https://github.com/steelbrain/exec/blob/v2.0.3/src/helpers.js#L81) breaks as `.replace()` isn't a funciton.

**Comment by steelbrain** [comment]
Thanks for the report, working on the fix
