### ISSUE TITLE
Error: Fatal error: exception End_of_file

### ISSUE THREAD

**Issue by MoOx** [steelbrain/exec#29]
```
Error: Fatal error: exception End_of_file
    at ChildProcess.<anonymous> (/Users/MoOx/setup/dotfiles/.atom/packages/linter-eslint/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

I am getting this each time I save a file in Atom. This error is triggered by linter-eslint, no idea why.
This make this plugin unusable. I tried to reinstall linter-eslint but no luck.

Any ideas?

**Comment by steelbrain** [comment]
This is actually a flow error, or any other package you're using that spawns programs written in OCAML. See https://github.com/facebook/flow/issues/937

**Comment by MoOx** [comment]
How can a flow error be reported by a stack trace that does not contain the path to flow?!
Anyway thanks for the point!

**Comment by MoOx** [comment]
pointer*

**Comment by steelbrain** [comment]
Well stack traces aren't really helpful in some cases, one of those cases is process execution. You have to follow your instincts and read the code the errors are pointing at to get the understanding of the error.

<img src="https://cloud.githubusercontent.com/assets/4278113/16078983/8e3b2996-32b6-11e6-9434-7fcf21395d4e.png">

As you can see in the code in image above, it's creating a new error from what it gets from stderr. Another thing you might wanna keep in mind is that written conversation don't convey tone very well, so while you could be writing `?!` in a funny tone, it could be misinterpreted as a rude one :)

**Comment by MoOx** [comment]
> it could be misinterpreted as a rude one :)

Sorry for that, it's not the idea behind the ?! 

Thanks for the explanation.
