### ISSUE TITLE
Use the npm-run module

### ISSUE THREAD

**Issue by nmn** [steelbrain/exec#3]
Consider using the npm-run module to automatically add the locally installed node_modules on the path.

**Comment by steelbrain** [comment]
Should the local `node_modules` be added as a fallback or priority? Or should we make that an option?

**Comment by nmn** [comment]
My guess is that it should be the priority. But an option works across the most projects.

**Comment by steelbrain** [comment]
Once #4 lands, you'll be able to execute local node modules, just make sure to pass `{ local: { directory: __dirname } }` as an option.

It'll automatically scan all the `node_modules/.bin` dirs and add them in path, you can also `append` or `prepend` them to the PATH using `local.prepend` option
