### ISSUE TITLE
flow checking all of node_modules

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/exec#43]
Currently `flow` is checking _all_ of `node_modules`, leading to initial start of the server being _incredibly_ slow. A simple ignore of the entire `node_modules` folder leads to issues with the `consistent-env` and `sb-npm-path` module types not being defined.

**Comment by steelbrain** [comment]
As discussed privately there's no apparent resolution to this. Flow only takes half a second on my mac while 1-2 minutes on windows because of presumed Microsoft Awesomeness 😛

**Comment by Arcanemagus** [comment]
You mean OCaml terribleness? 😛

**Comment by steelbrain** [comment]
Yeah that 😄 👍
