### ISSUE TITLE
Error: spawn ruby ENOENT using linter-ruby in Atom on Win 10

### ISSUE THREAD

**Issue by Xeboc** [steelbrain/exec#46]
Getting this error in Windows 10. Fixed by installing Ruby and adding to the path. This error probably just needs to be caught with a 'Hey, is ruby installed and in your path?' message.

```
Error: spawn ruby ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Requested by @Arcanemagus to file the issue with you, as it appears that exec isn't handling the error correctly.  AtomLinter/linter-ruby issue number [#80](https://github.com/AtomLinter/linter-ruby/issues/80)

**Comment by steelbrain** [comment]
Yo @Arcanemagus maybe you meant [`atom-linter`](https://github.com/steelbrain/atom-linter)?
This package is also used by cli node stuff so showing a message like that is probably out of scope of this one. But we can add it in `atom-linter`.

I've opened https://github.com/steelbrain/atom-linter/issues/148

**Comment by Arcanemagus** [comment]
Whoops, I guess I did 😛.

**Comment by Xeboc** [comment]
I suppose I shouldn't blindly open issues for other people, eh?  😄
