### ISSUE TITLE
Problem with cmdArgs under Window 8 64Bit

### ISSUE THREAD

**Issue by bmaschio** [steelbrain/exec#59]
@steelbrain 

Hi there I am having a bit of problem with calling the exec function 
that is called in the following way
where executablePath = "C:\Windows\system32\jolie.bat"
helpers.exec( executablePath, [ "--check", editor.getPath() ], { timeout: 10000 , stream: "both" } ).then ( data ) ->
it is returning not found program or batch file

I think this is given by  the wrong format of the variable parameters[2] (index.js) 
""C:\Windows\system32\jolie.bat "--check" "C:\Progetti\PortaleManutenzioneAndroid\Leonardo\leonardo.ol"""
According to this reference http://ss64.com/nt/cmd.html in the variable parameters[2]  is missing a " after the first the first term and there is a extra " on the end of the string
Regards
Balint

**Comment by Arcanemagus** [comment]
Let's continue the discussion in https://github.com/fmontesi/linter-jolie/issues/4 for now, as the linter _provider_ is running the program properly for me (nothing is wrong with the above command in the full context of it being a parameter to a call to `cmd.exe`).

**Comment by steelbrain** [comment]
I think this has been fixed after work from @Arcanemagus in master
