### ISSUE TITLE
Invoke API with elevated permissions

### ISSUE THREAD

**Issue by mschuchard** [steelbrain/exec#65]
I have been looking at the API and am trying to figure out a way to use to execute a command with elevated permissions (i.e. `sudo`). I am not able to see or think of a way given the API. Is there something I am missing?

**Comment by steelbrain** [comment]
Hi @mschuchard. Maybe you've been overthinking it :) Just append `sudo` to the command, and add

> `${password}\n`

to stdin and sudo should work just fine. Alternatively you can use one of those programs that show a sudo gui prompt and pipe the output through that. It's [`gksudo`](http://askubuntu.com/a/682966/175400) on ubuntu

**Comment by mschuchard** [comment]
So I am trying to do this with icinga2, which currently has a longstanding issue that they require elevated permissions for all of their binaries regardless of whether the binary actually needs it or not. I had tried prepending `sudo` to the command and got back `ENOENT` so I had assumed the first argument needed to be a filepath that is validated by `sb-exec`, but now that doesn't seem to be happening anymore so I think I was having some kind of string concat issue.

That stdin idea is pretty good. Thanks!

**Comment by mschuchard** [comment]
Ok now the error came back. So if I do something like:

```
var.exec('sudo /usr/sbin/icinga2', ['daemon', '-C', '--config', '/path/to/file'], {stdin: "password\n"})
```

then I get:

> Error: spawn sudo /usr/sbin/icinga2 ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Am I really allowed to prepend `sudo` to the command in the first argument?

**Comment by steelbrain** [comment]
Oh I'm sorry but it looks like you misunderstand the API. The first parameter should be the one and only command, you should write it as this instead
```js
var.exec('sudo', ['/usr/sbin/icinga2', 'daemon', ...])
```

**Comment by mschuchard** [comment]
Yeah I just realized that and was about to edit the question. I tried that and got back:

> Error: sudo: no tty present and no askpass program specified

which now becomes a problem outside of the API. Thanks again!
