### ISSUE TITLE
Specify encoding for stdin argument

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/exec#70]
From the discussion in https://github.com/AtomLinter/linter-phpcs/issues/235 it appears that the encoding should be being specified if we are passing in a string to `stdin`.

This might be expanded with the option of specifying the encoding, instead of just forcing it to be `utf8`.

**Comment by steelbrain** [comment]
Instead of having an option to specify stdin, I think it's just better to support Buffers
